cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: AKIA3ZGVXYFSJYGWCPHW
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/810049585508/teste-teste
